[package]
name = "backend"
version = "0.1.0"
authors = ["Aleksander Wawrzyniak <aleksander.wawrzyniak98@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
